import{useEffect,useMemo,useRef,useState}from'react';import maplibregl,{Map as MlMap}from'maplibre-gl';import{uploadRoute,preview,generate,getJob,type Frame,type RouteUpload,type Settings}from'./api';import{frameRing,moveFrame,orientFrame}from'./frame';
const mapStyle='https://demotiles.maplibre.org/style.json';
export default function App(){const node=useRef<HTMLDivElement>(null),map=useRef<MlMap|null>(null);const drag=useRef<{lng:number;lat:number}|null>(null);const[data,setData]=useState<RouteUpload>();const[frame,setFrame]=useState<Frame>();const[initial,setInitial]=useState<Frame>();const[layers,setLayers]=useState({route:true,roads:true,buildings:true});const[width,setWidth]=useState(1.5);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[warnings,setWarnings]=useState<string[]>([]);const[job,setJob]=useState<{id:string;status:string;progress:number;url?:string}>();
useEffect(()=>{if(!node.current)return;const m=map.current=new maplibregl.Map({container:node.current,style:mapStyle,center:[0,20],zoom:2});m.addControl(new maplibregl.NavigationControl());return()=>m.remove()},[]);
const settings=useMemo<Settings|undefined>(()=>frame?{frame,layers,route_width_mm:width}:undefined,[frame,layers,width]);
useEffect(()=>{const m=map.current;if(!m||!data||!frame)return;const sync=()=>{const shapes:[string,GeoJSON.GeoJSON][]=[['route',data.geojson],['frame',{type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[frameRing(frame)]}}]];for(const[id,g]of shapes){const source=m.getSource(id)as maplibregl.GeoJSONSource|undefined;if(source)source.setData(g);else{m.addSource(id,{type:'geojson',data:g});m.addLayer(id==='route'?{id,type:'line',source:id,paint:{'line-color':'#ff5a45','line-width':5}}:{id,type:'fill',source:id,paint:{'fill-color':'#3b82f6','fill-opacity':.16,'fill-outline-color':'#2563eb'}})}};m.on('mouseenter','frame',()=>m.getCanvas().style.cursor='grab')};m.isStyleLoaded()?sync():m.once('load',sync)},[data,frame]);
useEffect(()=>{const m=map.current;if(!m||!frame)return;const down=(e:maplibregl.MapMouseEvent)=>{if(m.queryRenderedFeatures(e.point,{layers:['frame']}).length){drag.current={lng:e.lngLat.lng,lat:e.lngLat.lat};m.dragPan.disable()}};const move=(e:maplibregl.MapMouseEvent)=>{if(!drag.current)return;setFrame(x=>x&&moveFrame(x,e.lngLat.lng-drag.current!.lng,e.lngLat.lat-drag.current!.lat));drag.current={lng:e.lngLat.lng,lat:e.lngLat.lat}};const up=()=>{drag.current=null;m.dragPan.enable()};m.on('mousedown',down);m.on('mousemove',move);m.on('mouseup',up);return()=>{m.off('mousedown',down);m.off('mousemove',move);m.off('mouseup',up)}},[frame?.orientation]);
useEffect(()=>{if(!job||['complete','failed'].includes(job.status))return;const timer=setTimeout(async()=>{try{const j=await getJob(job.id);setJob({id:job.id,status:j.status,progress:j.progress??0,url:j.result_url});setWarnings(j.warnings??[])}catch(e){setError(String(e))}},1000);return()=>clearTimeout(timer)},[job]);
async function upload(file?:File){if(!file)return;setBusy('Uploading GPX…');setError('');try{const d=await uploadRoute(file);setData(d);setFrame(d.suggested_frame);setInitial(d.suggested_frame);map.current?.fitBounds([[d.bounds[0],d.bounds[1]],[d.bounds[2],d.bounds[3]]],{padding:80})}catch(e){setError(String(e))}finally{setBusy('')}}
async function showPreview(){if(!data||!settings)return;setBusy('Loading preview…');try{const p=await preview(data.route_id,settings);setWarnings(p.warnings??[])}catch(e){setError(String(e))}finally{setBusy('')}}
async function start(){if(!data||!settings)return;setBusy('Starting…');try{const j=await generate(data.route_id,settings);setJob({id:j.job_id,status:'queued',progress:0})}catch(e){setError(String(e))}finally{setBusy('')}}
return <main><header><div><h1>MemoryMap Studio</h1><p>Place your route, choose the print area, and generate a layered 3MF.</p></div><label className="upload">Upload GPX<input type="file" accept=".gpx,application/gpx+xml" onChange={e=>upload(e.target.files?.[0])}/></label></header><section><div className="map" ref={node}>{!data&&<div className="empty">Upload a GPX route to begin</div>}</div><aside><h2>Print frame</h2><div className="seg"><button className={frame?.orientation==='landscape'?'on':''} onClick={()=>setFrame(f=>f&&orientFrame(f,'landscape'))}>Landscape</button><button className={frame?.orientation==='portrait'?'on':''} onClick={()=>setFrame(f=>f&&orientFrame(f,'portrait'))}>Portrait</button></div><button className="quiet" onClick={()=>setFrame(initial)}>Reset to route</button><Field label="Print width (mm)" value={frame?.print_width_mm??240} change={v=>setFrame(f=>f&&({...f,print_width_mm:v}))}/><Field label="Print height (mm)" value={frame?.print_height_mm??190} change={v=>setFrame(f=>f&&({...f,print_height_mm:v}))}/><Field label="Margin (mm)" value={frame?.margin_mm??8} change={v=>setFrame(f=>f&&({...f,margin_mm:v}))}/><Field label="Route width (mm)" value={width} step={.1} change={setWidth}/><h2>Layers</h2>{(['route','roads','buildings']as const).map(k=><label className="check" key={k}><input type="checkbox" checked={layers[k]} onChange={e=>setLayers({...layers,[k]:e.target.checked})}/>{k}</label>)}<div className="actions"><button disabled={!data||!!busy} onClick={showPreview}>Preview details</button><button className="primary" disabled={!data||!!busy} onClick={start}>Generate 3MF</button></div>{busy&&<p className="status">{busy}</p>}{job&&<div className="job"><b>{job.status}</b><progress max="100" value={job.progress}/>{job.url&&<a href={job.url}>Download 3MF</a>}</div>}{warnings.map((w,i)=><p className="warn" key={i}>{w}</p>)}{error&&<p className="error">{error}</p>}</aside></section></main>}
function Field({label,value,change,step=1}:{label:string;value:number;change:(v:number)=>void;step?:number}){return <label className="field"><span>{label}</span><input type="number" min="0" step={step} value={value} onChange={e=>change(+e.target.value)}/></label>}
